In [13]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(arr)
print(np.__version__)

[1 2 3 4 5 6 7 8 9]
2.2.3


# zeros - elementlari 0 bo'lgan massivni yaratadi

In [14]:
arr2 = np.zeros((2, 4))
print(arr2)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


# ones - elementlari 1 bo'lgan massiv yartib beradi 

In [12]:
arr3 = np.ones((3, 5))
print(arr3)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


# full - tanlangan son bilan massiv yaratadi

In [19]:
arr4 = np.full((2, 4), 13)
print(arr4)

[[13 13 13 13]
 [13 13 13 13]]


# eye - berilgan o'lchamdagi, berilgan qiymat indexs qiymatidan boshlab diaganal elemtlari 1 ga teng massivni yaratib beradi

In [32]:
arr5 = np.eye(4, 8, 2)
print(arr5)

[[0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]]


# identity - kvadarat shakilda diaganali 1 ga teng matritsa yaratadi

In [35]:
arr6 = np.identity(3)
print(arr6)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# empty - berilgan o'lchamdagi bo'sh massivni yaratadi

In [40]:
arr7 = np.empty((2, 4))
print(arr7)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


# arange - berilgan orqaliqda massivni yaratadi. 1 dan 10 gacha bo'lgan sonlar bilan 2 qadam bilan massiv yaratadi

In [41]:
arr8 = np.arange(1, 12, 2)
print(arr8)

[ 1  3  5  7  9 11]


# linspace - 2 ta chegara orasida belgilanga miqdoradgi lelemtdan iborat massiv yaratadi

In [45]:
arr9 = np.linspace(1, 2, 5)
print(arr9)

[1.   1.25 1.5  1.75 2.  ]


# logspace - logarifmik shakilda taqsimlangan sonlar massivini yaratadi

In [48]:
arr10 = np.logspace(1, 3, 8)
print(arr10)

[  10.           19.30697729   37.2759372    71.9685673   138.94954944
  268.26957953  517.94746792 1000.        ]


# meshgrid - 2 yoki undan ko'p massivdan koordinatalar to'plamini yaratadi

In [55]:
x = np.array([1, 2, 3])
y = np.array([6, 7, 8, 1])
z = np.array([4, 5, 6])
X, Y, Z= np.meshgrid(x, y, z)
print(X)
print(Y)


[[[1 1 1]
  [2 2 2]
  [3 3 3]]

 [[1 1 1]
  [2 2 2]
  [3 3 3]]

 [[1 1 1]
  [2 2 2]
  [3 3 3]]

 [[1 1 1]
  [2 2 2]
  [3 3 3]]]
[[[6 6 6]
  [6 6 6]
  [6 6 6]]

 [[7 7 7]
  [7 7 7]
  [7 7 7]]

 [[8 8 8]
  [8 8 8]
  [8 8 8]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


# indices - berilgan o‘lchamdagi massiv koordinatalarini hosil qiladi.

In [61]:
arr11 = np.indices((2, 8))
print(arr11)

[[[0 0 0 0 0 0 0 0]
  [1 1 1 1 1 1 1 1]]

 [[0 1 2 3 4 5 6 7]
  [0 1 2 3 4 5 6 7]]]


# diag - massivning diagonali bo‘yicha elementlarni oladi yoki diagonal matritsa yaratadi.

In [65]:
arr12 = np.diag([1, 2, 3, 4])
print(arr12)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


# diagfloat - berilgan massiv elementlarini diagonali bo‘yicha joylashtirib matritsa yaratadi.

In [63]:
arr13 = np.diagflat([1, 2, 3, 5])
print(arr13)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 5]]
