In [21]:
print("Salom")

Salom


In [22]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [23]:

import numpy as np

In [24]:
l = ['olma', 'nok', 45]
data = np.array(l)

In [25]:
type(l)

list

In [26]:
type(data)

numpy.ndarray

In [27]:
data

array(['olma', 'nok', '45'], dtype='<U21')

In [28]:
l1 = (1, 2, 3, 4, 5, 6)
data2 = np.array(l1)
type(data2)
data2

array([1, 2, 3, 4, 5, 6])

In [29]:
data2.ndim

1

In [30]:
newdata = [
    [1, 2, 3, 4, 5, 6], 
    [7 , 8, 9, 10, 11, 12]
    ]

arraydata = np.array(newdata)
arraydata.ndim
print(arraydata)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [31]:
arraydata.shape

(2, 6)

In [32]:
arraydata.size

12

In [33]:
zerrosdata = np.zeros((2, 5))
zerrosdata

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [34]:
twozeros = np.zeros(shape=(2, 4))
twozeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

# zrro bizga 0 dan oborat array yartib beradi


In [35]:
data3 = np.arange(10)
data3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])