In [13]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(arr)
print(np.__version__)

[1 2 3 4 5 6 7 8 9]
2.2.3


# zeros - elementlari 0 bo'lgan massivni yaratadi

In [14]:
arr2 = np.zeros((2, 4))
print(arr2)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


# ones - elementlari 1 bo'lgan massiv yartib beradi 

In [12]:
arr3 = np.ones((3, 5))
print(arr3)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


# full - tanlangan son bilan massiv yaratadi

In [19]:
arr4 = np.full((2, 4), 13)
print(arr4)

[[13 13 13 13]
 [13 13 13 13]]


# eye - berilgan o'lchamdagi, berilgan qiymat indexs qiymatidan boshlab diaganal elemtlari 1 ga teng massivni yaratib beradi

In [32]:
arr5 = np.eye(4, 8, 2)
print(arr5)

[[0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]]


# identity - kvadarat shakilda diaganali 1 ga teng matritsa yaratadi

In [35]:
arr6 = np.identity(3)
print(arr6)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# empty - berilgan o'lchamdagi bo'sh massivni yaratadi

In [40]:
arr7 = np.empty((2, 4))
print(arr7)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
