# shape - massivni o'lchamini qaytaradi

In [28]:
import numpy as np

arr = np.array([
    [9, 0, 8], 
    [1, 2, 3]
    ])
print(arr.shape)

(2, 3)


# size - massivning jami elementlar sonini qaytaradi.

In [10]:
arr1 = np.array([8, 7, 6, 5, 0, 5])
print(arr1.size)

6


# ndim - massivni o'lchovini qaytaradi

In [8]:
print(arr.ndim)
print(arr1.ndim)

2
1


# dtype - masiv elementini ma'lumotlar turini qaytaradi

In [12]:
print(arr.dtype)
print(arr1.dtype)

int64
int64


# astype - boshqa ma'lumot turiga o'giradi

In [18]:
float_arr = arr.astype(str)
print(float_arr)
print(f"data taype = {float_arr.dtype}")

[['9' '0' '8']
 ['1' '2' '3']]
data taype = <U21


# ravel - elemetlarni bir o'lchamga (1D) ga o'tkazadi

In [19]:
print(arr.ravel())

[9 0 8 1 2 3]


# flatten - ravel bilan bir xil lekin nusxasini qaytaradi

In [20]:
print(arr.flatten())

[9 0 8 1 2 3]


# transpose - qator va ustinlarini alamashtiradi

In [2]:
print(arr.transpose())

[[9 1]
 [0 2]
 [8 3]]


# swapaxes - istalgan ikkita o'qini almashtiradi

In [17]:
arr2 = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])
print(np.swapaxes(arr2, 0, 1))

[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


# squeeze - bir o'lchamliy o'qlarni olib tashlaydi

In [23]:
arr3 = np.array([[
    [1],
    [3],
    [4]
]])
print(arr3.squeeze())

[1 3 4]


# expand_dims - massivga qo'shimcha o'q qo'shadi

In [27]:
print(np.expand_dims(arr, axis=0))

[[[9 0 8]
  [1 2 3]]]


# hstack - massivlarni yonma-yon birlashtiradi

In [34]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(np.hstack((a, b)))


[1 2 3 4 5 6]


# vstack - masivvlarni vertikal ravishda birlashtiradi

In [36]:
d = np.vstack((a, b))
print(d)

[[1 2 3]
 [4 5 6]]


# dstack - massivlarni uchunchi o'q bo'yicha birlashtiradi

In [37]:
c = np.dstack((a, b))
print(c)

[[[1 4]
  [2 5]
  [3 6]]]


# concatenate - masivlarni birlashtiradi

In [41]:
f = np.concatenate((a, b))
print(f)

[1 2 3 4 5 6]


# split - massivni teng bo'laklarga bo'ladi

In [64]:
arr5 = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(np.split(arr5, 4))  

[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]


# hsplit - massivni ustinlari bo'yicha bo'ladi

In [68]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(np.hsplit(arr, 3))  


[array([[1],
       [4]]), array([[2],
       [5]]), array([[3],
       [6]])]
