# take - berilgan indexdagi lementlarni olib beradi

In [7]:
import numpy as np
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80])
index_ = [0, 1, 5]
result = np.take(arr, index_)
print(result)


[10 20 60]


# put - berilgan indekslar bo‘yicha massivga yangi qiymatlar joylashtirish

In [6]:
value = [0, 9, 8]
result01 = np.put(arr, index_, value) 
print(arr)

[ 0  9 30 40 50  8 70 80]


# choose - berilgan indekslar bo‘yicha bir nechta massivdan elementlarni tanlash

In [12]:
a = np.array([10, 20, 30, 40])
b = np.array([12, 13, 14, 15])
c = np.array([21, 14, 15, 17])
choices = [a, b, c]
index02 = [2, 0, 1, 0]
result02 = np.choose(index02, choices)
print(result02)

[21 20 14 40]


# nonzero - 0 bo'lmagan elemetlarni indexsini qaytaradi

In [17]:
arr01 = np.array([1, 2, 0, 3, 8, 0, 0])
result03 = np.nonzero(arr01)
print(result03)

(array([0, 1, 3, 4]),)


# where - berilgan shartga kiradigan elemet indexslarini qaytaradi yo elelmt qo'shadi

In [21]:
result04 = np.where(arr01 > 1)
result05 = np.where(a > 30, 1, 0)
print(result04, result05)

(array([1, 3, 4]),) [0 0 0 1]


# extract - shary bo'yicha e'lemetlarni olish

In [23]:
result06 = np.extract(arr01 > 1, arr01)
print(result06)

[2 3 8]


# diagonal - matritsaning diagonal elementlarini olish

In [25]:
m = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 0, 1, 2],
    [0, 5, 3, 4]
])
result07 = np.diagonal(m)
print(result07)

[1 6 1 4]


# compress - berilgan shart bo‘yicha faqat mos keladigan elementlarni olish.

In [26]:
arr02 = np.array([1, 13, 14, 15, 7])
condition = [True, False, True, True, False]
result08 = np.compress(condition, arr02)
print(result08)

[ 1 14 15]
