# static va yig'indi funksiyalar

In [3]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])
b = np.array([1, 2, 3])

# 1. Summa (yig‘indi)
print(f"sum = {np.sum(a)}") 

# 2. Ko'paytma
print(f"prod = {np.prod(a)}")  

# 3. Kumulativ summa (yig‘indi)
print(f"cumsum = {np.cumsum(a)}")  # [ 1  3  6 1

# 4. Kumulativ ko'paytma
print(f"comprod = {np.cumprod(a)}")  # [  1   2   6  24

# 5. O‘rtacha qiymat
print(f"mean = {np.mean(a)}")  

# 6. Median (o‘rtacha qiymat tartib bo‘yicha)
print(f"median = {np.median(a)}")  

# 7. O‘rtacha qiymat (og‘irliklar bilan)
weights = np.array([1, 2, 3])
print(f"average = {np.average(b, weights=weights)}")  # 2.33333333333

# 8. Standart og‘ish 
print(f"std = {np.std(a)}")  # 1.41421356237

# 9. Dispersiya 
print(f"var = {np.var(a)}")  

# 10. Eng kichik qiymat
print(f"min = {np.min(a)}")

# 11. Eng katta qiymat
print(f"max = {np.max(a)}")

# 12. Eng katta va eng kichik qiymatlar farqi (peak-to-peak)
print(f"ptp = {np.ptp(a)}")

# 13. Foizli qiymatlar (percentile) - 50% median bilan bir xil
print(f"percentile = {np.percentile(a, 50)}")  

# 14. Kvantil - 0.5 kvantil ham median bilan bir xil
print(f"quantile = {np.quantile(a, 0.5)}")  


sum = 15
prod = 120
cumsum = [ 1  3  6 10 15]
comprod = [  1   2   6  24 120]
mean = 3.0
median = 3.0
average = 2.3333333333333335
std = 1.4142135623730951
var = 2.0
min = 1
max = 5
ptp = 4
percentile = 3.0
quantile = 3.0


# Sorting funksiyalar

In [19]:
import numpy as np

a = np.array([3, 1, 4, 1, 5, 9, 2, 6, 5, 3])

# 1. Oddiy saralash
print(f"sort = {np.sort(a)}")  


# 2. Indekslarni qaytaruvchi saralash
print(f"argsort = {np.argsort(a)}")  

# 3. Lexikografik saralash (ko‘p o‘lchamli massivlar uchun)
names = ('John', 'Jane', 'Alex', 'Bob')
ages = np.array([25, 30, 20, 22])
heights = np.array([175, 160, 180, 170])

sorted_indices = np.lexsort((heights, ages))  
print(f"lexsort = {sorted_indices}")  

# 4. Qidirish (searchsorted) - qaysi indeksga joylash kerakligini aniqlash
sorted_array = np.array([1, 3, 4, 7, 9])
print(f"searchsorted = {np.searchsorted(sorted_array, 7)}")  


# 5. Tanlangan qiymatlar bo‘yicha ajratish (partition)
b = np.array([9, 7, 5, 3, 1])
print(f"partition = {np.partition(b, 1)}")  

# 6. Indekslangan ajratish (argpartition)
print(f"argpartition = {np.argpartition(b, 2)}")  


sort = [1 1 2 3 3 4 5 5 6 9]
argsort = [1 3 6 0 9 2 8 4 7 5]
lexsort = [2 3 0 1]
searchsorted = 3
partition = [1 3 5 7 9]
argpartition = [4 3 2 1 0]


# O'zaro moslik va tekshirish funksiyalari

In [21]:
import numpy as np

# Barcha elementlar True yoki yo‘qligini tekshiradi
a = np.array([True, True, False])
b = np.array([1, 2, 3])
print(f"all = {np.all(a)}")  
print(f"all = {np.all(b)}") 

# Kamida bitta element True yoki yo‘qligini tekshiradi
print(np.any(a))        
c = np.array([0, 0, 0])
print(f"any = {np.any(c)}")  

# Cheksiz yoki NaN bo‘lmagan elementlarni aniqlaydi
d = np.array([1, np.nan, np.inf, -np.inf, 3])
print(f"isfinite = {np.isfinite(d)}")  

# Cheksiz elementlarni aniqlaydi
print(F"isinf = {np.isinf(d)}") 

# NaN elementlarni aniqlaydi
print(f"isnan = {np.isnan(d)}") 

# Skalyar ekanligini tekshiradi
print(f"isscalar = {np.isscalar(42)}") 
print(f"isscalar = {np.isscalar(np.array([42]))}")  

# Kompleks elementlarni aniqlaydi
e = np.array([1+2j, 3, 4j, 5])
print(f"iscomplex = {np.iscomplex(e)}")

# Haqiqiy elementlarni aniqlaydi
print(f"isreal = {np.isreal(e)}")

# Haqiqiy massiv ekanligini tekshiradi
f = np.array([1.5, 2, 3])
g = np.array([1+2j, 3, 4j])
print(f"isrealobj = {np.isrealobj(f)}") 
print(f"isrealobj = {np.isrealobj(g)}")  

# Kompleks massiv ekanligini tekshiradi
print(f"iscomplexobj = {np.iscomplexobj(f)}")  
print(f"iscomplexobj = {np.iscomplexobj(g)}") 



all = False
all = True
True
any = False
isfinite = [ True False False False  True]
isinf = [False False  True  True False]
isnan = [False  True False False False]
isscalar = True
isscalar = False
iscomplex = [ True False  True False]
isreal = [False  True False  True]
isrealobj = True
isrealobj = False
iscomplexobj = False
iscomplexobj = True


# Bitwise (bit bo‘yicha) operatsiyalar

In [22]:
import numpy as np

# Bitwise AND (elementlar bo‘yicha mantiqiy VA amali)
x = np.array([0b1100, 0b1010, 0b0111])
y = np.array([0b1010, 0b1100, 0b0011])
print(f"bitwise_and = {np.bitwise_and(x, y)}")  

# Bitwise OR (elementlar bo‘yicha mantiqiy YOKI amali)
print(f"bitwise_or = {np.bitwise_or(x, y)}")  

# Bitwise XOR (elementlar bo‘yicha mantiqiy XOR amali)
print(f"bitwise_xor = {np.bitwise_xor(x, y)}")  

# Bitwise INVERT (elementlarni teskari o‘zgartirish)
z = np.array([0, 1, 2, 3, 4])
print(f"invert = {np.invert(z)}")  

# LEFT SHIFT (bitlarni chapga siljitish)
a = np.array([1, 2, 3])
print(f"left_shift = {np.left_shift(a, 2)}")  # 2 ta pozitsiyaga chapga siljitish

# RIGHT SHIFT (bitlarni o‘ngga siljitish)
b = np.array([16, 32, 64])
print(f"right_shift = {np.right_shift(b, 2)}")  # 2 ta pozitsiyaga o‘ngga siljitish


bitwise_and = [8 8 3]
bitwise_or = [14 14  7]
bitwise_xor = [6 6 4]
invert = [-1 -2 -3 -4 -5]
left_shift = [ 4  8 12]
right_shift = [ 4  8 16]


# Chiziqli algebra funksiyalari (Linear Algebra)

In [23]:
import numpy as np

# 1. numpy.dot() - Skalyar ko'paytirish yoki matritsalar ko'paytmasi
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print(f"dot = \n{np.dot(A, B)}")  

# 2. numpy.matmul() - Matritsalar ko'paytmasi (yangi @ operatori bilan bir xil)
print(f"matmul = \n{np.matmul(A, B)}") 

# 3. numpy.vdot() - Vektorlar skalyar ko'paytmasi (ichki ko'paytirish)
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
print(f"vdot = {np.vdot(x, y)}") 

# 4. numpy.inner() - Ichki ko‘paytirish (skalyar yoki vektorlar o‘rtasidagi hosila)
print(f"inner = {np.inner(x, y)}")  

# 5. numpy.outer() - Tashqi ko‘paytirish (matritsa hosil qiladi)
print(f"outer = \n{np.outer(x, y)}")

# 6. numpy.linalg.norm() - Vektor yoki matritsa normasi (vektor uzunligi)
print(f"norm = {np.linalg.norm(x)}") 

# 7. numpy.linalg.det() - Determinantni hisoblash
print(f"det = {np.linalg.det(A)}")  

# 8. numpy.linalg.inv() - Matritsaning teskari matritsasini hisoblash
print(f"inv = \n{np.linalg.inv(A)}")  

# 9. numpy.linalg.eig() - Matritsaning o‘z qiymatlari va o‘z vektorlari
eigvals, eigvecs = np.linalg.eig(A)
print(f"eigvals = {eigvals}")  
print(f"eigvecs = \n{eigvecs}")  

# 10. numpy.linalg.svd() - Matritsaning Singular Qiymat Decomposition (SVD)
U, S, Vt = np.linalg.svd(A)
print(f"SVD U = \n{U}")  
print(f"SVD S = {S}")  
print(f"SVD Vt = \n{Vt}")  

# 11. numpy.linalg.qr() - QR dekompozitsiyasi (ortogonal va uchburchak matritsalarga ajratish)
Q, R = np.linalg.qr(A)
print(f"QR Q = \n{Q}")  
print(f"QR R = \n{R}")  

# 12. numpy.linalg.solve() - Chiziqli tenglamalar sistemasini yechish (Ax = b)
b = np.array([5, 6])
x = np.linalg.solve(A, b)
print(f"solve = {x}")  

# 13. numpy.linalg.pinv() - Psevdoinvers matritsani hisoblash
print(f"pinv = \n{np.linalg.pinv(A)}")  


dot = 
[[19 22]
 [43 50]]
matmul = 
[[19 22]
 [43 50]]
vdot = 32
inner = 32
outer = 
[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]
norm = 3.7416573867739413
det = -2.0000000000000004
inv = 
[[-2.   1. ]
 [ 1.5 -0.5]]
eigvals = [-0.37228132  5.37228132]
eigvecs = 
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]
SVD U = 
[[-0.40455358 -0.9145143 ]
 [-0.9145143   0.40455358]]
SVD S = [5.4649857  0.36596619]
SVD Vt = 
[[-0.57604844 -0.81741556]
 [ 0.81741556 -0.57604844]]
QR Q = 
[[-0.31622777 -0.9486833 ]
 [-0.9486833   0.31622777]]
QR R = 
[[-3.16227766 -4.42718872]
 [ 0.         -0.63245553]]
solve = [-4.   4.5]
pinv = 
[[-2.   1. ]
 [ 1.5 -0.5]]


# Random sonlar generatsiyasi (NumPy Random)

In [24]:
import numpy as np

# 1. numpy.random.rand() - [0, 1] oralig‘ida bir xil taqsimlangan tasodifiy sonlar generatsiyasi
print(f"rand = {np.random.rand()}") 
print(f"rand(2,3) = \n{np.random.rand(2, 3)}")  

# 2. numpy.random.randn() - Normal (Gauss) taqsimot bo‘yicha tasodifiy sonlar generatsiyasi
print(f"randn = {np.random.randn()}")
print(f"randn(3,3) = \n{np.random.randn(3, 3)}") 

# 3. numpy.random.randint() - Berilgan [low, high) oralig‘ida butun sonlar generatsiyasi
print(f"randint(1, 10) = {np.random.randint(1, 10)}") 
print(f"randint(5, 15, size=(2,3)) = \n{np.random.randint(5, 15, size=(2,3))}")  

# 4. numpy.random.random() - [0,1] oralig‘ida tasodifiy son generatsiyasi (rand bilan bir xil)
print(f"random = {np.random.random()}")  

# 5. numpy.random.choice() - Berilgan massivdan tasodifiy element tanlash
arr = np.array([10, 20, 30, 40, 50])
print(f"choice = {np.random.choice(arr)}")  
print(f"choice(3) = {np.random.choice(arr, size=3, replace=False)}")  

# 6. numpy.random.permutation() - Berilgan massivni tasodifiy aralashtirish (yangi nusxa qaytaradi)
print(f"permutation = {np.random.permutation(arr)}")  

# 7. numpy.random.shuffle() - Berilgan massivni joyida (in-place) aralashtirish
np.random.shuffle(arr)
print(f"shuffle = {arr}")  

# 8. numpy.random.seed() - Tasodifiy sonlarni qayta takrorlanadigan qilib qo‘yish
np.random.seed(42)  
print(f"seed rand(3) = {np.random.rand(3)}")  


rand = 0.6083462839930919
rand(2,3) = 
[[0.81938953 0.28458141 0.7248775 ]
 [0.84734132 0.3461566  0.81879789]]
randn = 0.6847081388614619
randn(3,3) = 
[[-0.55766889  1.14693015 -2.05625683]
 [-1.64627122  0.52625892 -0.36744784]
 [ 0.31864851  0.0090227   1.73890398]]
randint(1, 10) = 7
randint(5, 15, size=(2,3)) = 
[[11  8  6]
 [11  5 12]]
random = 0.5869608591280561
choice = 30
choice(3) = [30 40 50]
permutation = [20 50 10 30 40]
shuffle = [10 40 50 30 20]
seed rand(3) = [0.37454012 0.95071431 0.73199394]


# Boolean operatsiyalar

In [25]:
import numpy as np

# 1. numpy.logical_and() - Ikkita massivni elementma-element mantiqiy VA (AND) amali
a = np.array([True, False, True, False])
b = np.array([True, True, False, False])
print(f"logical_and = {np.logical_and(a, b)}")  

# 2. numpy.logical_or() - Ikkita massivni elementma-element mantiqiy YOKI (OR) amali
print(f"logical_or = {np.logical_or(a, b)}")

# 3. numpy.logical_not() - Massiv elementlarini inkor qilish (NOT)
print(f"logical_not = {np.logical_not(a)}") 

# 4. numpy.logical_xor() - Ikkita massivni elementma-element mantiqiy XOR amali
print(f"logical_xor = {np.logical_xor(a, b)}") 

# 5. numpy.allclose() - Ikkita massivning elementlari yaqinligini tekshirish (float qiymatlar uchun)
x = np.array([1.0, 2.001, 3.0])
y = np.array([1.0, 2.002, 3.0])
print(f"allclose = {np.allclose(x, y, atol=0.01)}")  # True, agar barcha elementlar yaqin bo'lsa

# 6. numpy.isclose() - Elementlar juftlik bo‘yicha yaqinligini tekshirish
print(f"isclose = {np.isclose(x, y, atol=0.001)}") 



logical_and = [ True False False False]
logical_or = [ True  True  True False]
logical_not = [False  True False  True]
logical_xor = [False  True  True False]
allclose = True
isclose = [ True  True  True]


# Faylga yozish va o‘qish 

In [26]:
import numpy as np

# 1. numpy.save() & numpy.load() - Massivni .npy formatida saqlash va yuklash
arr = np.array([[1, 2, 3], [4, 5, 6]])
np.save("data.npy", arr)
loaded_arr = np.load("data.npy")
print(f"load = \n{loaded_arr}")

# 2. numpy.savetxt() & numpy.loadtxt() - Matn fayliga saqlash va yuklash
np.savetxt("data.txt", arr, delimiter=",", fmt="%d")
loaded_txt = np.loadtxt("data.txt", delimiter=",", dtype=int)
print(f"loadtxt = \n{loaded_txt}")

# 3. numpy.genfromtxt() - Xatolarni to‘g‘rilab matn faylidan yuklash
data = np.genfromtxt("data.txt", delimiter=",", dtype=int, filling_values=-1)
print(f"genfromtxt = \n{data}")

# 4. numpy.fromfile() & numpy.tofile() - Ikkilik faylga yozish va o‘qish
arr.tofile("data.bin")
loaded_bin = np.fromfile("data.bin", dtype=int)
print(f"fromfile = \n{loaded_bin}")

arr.tofile("data_text.txt", sep=",", format="%d")

# 5. numpy.logical_and() - Ikkita massivni elementma-element mantiqiy VA (AND) amali
a = np.array([True, False, True, False])
b = np.array([True, True, False, False])
print(f"logical_and = {np.logical_and(a, b)}")

# 6. numpy.logical_or() - Ikkita massivni elementma-element mantiqiy YOKI (OR) amali
print(f"logical_or = {np.logical_or(a, b)}")

# 7. numpy.logical_not() - Massiv elementlarini inkor qilish (NOT)
print(f"logical_not = {np.logical_not(a)}")

# 8. numpy.logical_xor() - Ikkita massivni elementma-element mantiqiy XOR amali
print(f"logical_xor = {np.logical_xor(a, b)}")

# 9. numpy.allclose() - Ikkita massivning elementlari yaqinligini tekshirish (float qiymatlar uchun)
x = np.array([1.0, 2.001, 3.0])
y = np.array([1.0, 2.002, 3.0])
print(f"allclose = {np.allclose(x, y, atol=0.01)}")

# 10. numpy.isclose() - Elementlar juftlik bo‘yicha yaqinligini tekshirish
print(f"isclose = {np.isclose(x, y, atol=0.001)}")


load = 
[[1 2 3]
 [4 5 6]]
loadtxt = 
[[1 2 3]
 [4 5 6]]
genfromtxt = 
[[1 2 3]
 [4 5 6]]
fromfile = 
[1 2 3 4 5 6]
logical_and = [ True False False False]
logical_or = [ True  True  True False]
logical_not = [False  True False  True]
logical_xor = [False  True  True False]
allclose = True
isclose = [ True  True  True]


# NumPy Masked Arrays

In [27]:
import numpy as np

# 1. numpy.ma.masked_array()
# Berilgan ma'lumotlardan masklangan massiv yaratadi.
data = np.array([1, 2, 3, -1, 5])
masked_arr = np.ma.masked_array(data, mask=[0, 0, 0, 1, 0])
print("Masked Array:")
print(masked_arr)

# 2. numpy.ma.getmask()
# Masklangan massivning maskasini qaytaradi.
mask = np.ma.getmask(masked_arr)
print("Mask:")
print(mask)

# 3. numpy.ma.masked_equal()
# Berilgan qiymatga teng bo'lgan elementlarni mask qiladi.
data2 = np.array([1, 2, 3, 4, 5, 3])
masked_eq = np.ma.masked_equal(data2, 3)  # 3 ga teng bo'lgan elementlarni mask qiladi
print("Masked Equal (3):")
print(masked_eq)

# 4. numpy.ma.masked_less()
# Berilgan qiymatdan kichik bo'lgan elementlarni mask qiladi.
data3 = np.array([1, 4, 7, -2, 5, 0])
masked_less = np.ma.masked_less(data3, 2)  # 2 dan kichik bo'lgan elementlarni mask qiladi
print("Masked Less (2):")
print(masked_less)

# 5. numpy.ma.masked_greater()
# Berilgan qiymatdan katta bo'lgan elementlarni mask qiladi.
data4 = np.array([2, 5, 8, 1, 6])
masked_greater = np.ma.masked_greater(data4, 5)  # 5 dan katta bo'lgan elementlarni mask qiladi
print("Masked Greater (5):")
print(masked_greater)


Masked Array:
[1 2 3 -- 5]
Mask:
[False False False  True False]
Masked Equal (3):
[1 2 -- 4 5 --]
Masked Less (2):
[-- 4 7 -- 5 --]
Masked Greater (5):
[2 5 -- 1 --]
